quotes:
  - "В каждом человеке — солнце. Только дайте ему светить. Сократ"
  - "Железо так говорило магниту: 'Больше всего я тебя ненавижу за то,что ты притягиваешь,не имея достаточно сил,чтобы тащить за собой'. Ницше"
  - "Люди которые любят шоколад, гораздо меньше страдают от инсультов"
  - "Немецкий изобретатель Дрейз изобрел пишущую машинку, мясорубку, велосипед, дрезину (которую и назвали в его честь)"
  - "У норок одно занятие Сексом продолжается в среднем около 8 часов"
  - "Королева Мадагаскара Ранавалона приказывала казнить своих подданных, если те являлись к ней во снах без ее разрешения"
  - "Около 1 000 000 деревьев на земле, выросли благодаря белкам, которые зарыли орехи в землю, и забыли, где они это сделали"
  - "Если человека попросить загадать число от 1 до 10, с наибольшей вероятностью он загадает семь"
  - "Парацетамол - один из ядовитейших препаратов на современном фармацевтическом рынке. В европе на его использование наложен запрет"
  - "1830-х годах кетчуп продавался как лекарство"
  - "Логотип для 'Чупа-чупс' нарисовал Сальвадор Дали"
  - "Не тряси зеленую яблоню – когда яблоко созреет, оно упадет само. Все происходит так, как должно быть и в тот момент, когда это нужно"
  - "Музыка доставляет мозгу такое же удовольствие, как Секс"
  - "Потребуется 1200000 комаров, кусающих друг за другом, чтоб выпить всю кровь у среднестатистического человека"
  - "Через минуту пребывания в темноте чувствительность глаз к свету возрастает в 10 раз, через 20 мин. — в 6000 раз"
  - "Тойота изначально была компанией по производству автоматических ткацких станков.А значок означал ни иное,как нитку,пропущенную в ушко иголки"
  - "В первом тысячелетии было 365 250 дней. Во втором - 365 237. В третьем будет 365 242 дня"
  - "Среднестатистический человек имеет продолжительность жизни 2 475 576 000 секунд. Радуйтесь жизни, цените каждое ее мгновение"
  - "Движение земной коры привели к тому, что побережье Европы отодвинулось от Америки на 1 м за последние 25 лет"
  - "Знаменитая актриса XIX века Сара Бернар стала первой женщиной, осмелившейся носить мужские брюки"
  - "Днепропетровская область — одна из самых золотоносных в Украине"
  - "Проснуться утром яблоки помогают лучше, чем кофе"
  - "За последний век яркость Солнца выросла на один процент"
  - "Уолт Дисней,создатель Микки Мауса боялся мышей"